Add paperclip
sd-kin/vote pull request #86
Opened 2017-03-08 12:18 UTC by sd-kin

2017-03-08 13:00 UTC, kirushik requested changes
I don't see any integration test for images attaching.
Since it's a pretty advanced (and fragile) thing, with lots of functionality "hidden" in gems — I think it will make sense to test image uploading with PhantomJS.

What do you think?

2017-03-08 13:00 UTC, kirushik commented on app/models/concerns/imageable.rb
> +    has_many :images, as: :imageable, dependent: :destroy
Will actual files be destroyed here, or only their database handles?

2017-03-08 13:00 UTC, kirushik commented on config/routes.rb
> +      delete 'delete_image'
I didn't see this action in `PollsController`. Am I missing something?

2017-03-08 13:57 UTC, sd-kin commented on app/models/concerns/imageable.rb
> +    has_many :images, as: :imageable, dependent: :destroy
Paperclip take care about actual files, so both actual files and database handles will be deleted. I doubt it myself, but it just works.

2017-03-08 13:58 UTC, sd-kin commented on config/routes.rb
> +      delete 'delete_image'
nope, I forgot to glean up.

2017-03-10 15:41 UTC, kirushik approved these changes

2017-03-10 15:41 UTC, kirushik commented on config/environments/test.rb
> +  Paperclip::Attachment.default_options[:url]  = '/test_files/:class/:id_partition/:style/:filename'
Why do you think this is better?
I can't find anyone messing with their `:url` option of Paperclip for testing purposes (see [here](https://github.com/search?utf8=%E2%9C%93&q=Paperclip%3A%3AAttachment.default_options%5B%3Aurl%5D+filename%3Atest.rb&type=Code&ref=searchresults))

2017-03-11 17:34 UTC, merged